version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: agung
                uid: 1000
        image: pharmacy-services:1.0
        container_name: pharmacy-services
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            APP_ENV: local
            APP_URL: http://localhost
            DB_HOST: mysql-pharmacy-services  
            DB_PORT: 3307
            DB_DATABASE: pharmacy_services
            DB_USERNAME: root
            DB_PASSWORD: root
        networks:
            - pharmacy-services-network

    nginx:
        image: nginx:alpine
        container_name: web-server-pharmacy-services
        restart: unless-stopped
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - pharmacy-services-network

    mysql-pharmacy-services:  # Ganti container_name menjadi mysql-pharmacy-services
        image: mysql:8.3
        container_name: mysql-pharmacy-services  # Ganti nama container
        restart: unless-stopped
        ports:
            - "3307:3306"  
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pharmacy_services
        networks:
            - pharmacy-services-network

networks:
    pharmacy-services-network:
        driver: bridge

volumes:
    mysql_data:
        driver: bridge
